"""Follow-up opportunities: what a terminal result leaves worth asking.

`docs/02-architecture.md` §3 — every terminal transition emits a follow-up,
and the Theorist's next cycle reads them. This is the generational loop, and
the reason a refutation is a terminal *success* rather than a dead end.

Generated by code, not by a model. The rules below are deterministic functions
of how the work ended, and that matters for two reasons: a model asked "what
next?" after a null result reliably suggests trying again with more data, and
a follow-up whose provenance is a model's enthusiasm is not evidence that the
institution learned anything. These carry the hypothesis and the result that
motivated them, so a second-generation question can be traced to the
first-generation finding that produced it.

A follow-up is a *seed*, not a hypothesis. The Theorist turns one into a
falsifiable statement, and the parent link is what makes the descent visible
in the genealogy.
"""

from __future__ import annotations

from dataclasses import dataclass

from nullius.db.enums import DerivationKind, HypothesisState, Verdict

__all__ = ["FollowUpSeed", "seeds_for"]


@dataclass(frozen=True, slots=True)
class FollowUpSeed:
    """A question this result leaves open."""

    kind: str
    prompt: str
    derivation: DerivationKind
    """How a hypothesis built from this seed descends from its parent."""

    def as_dict(self) -> dict[str, str]:
        return {"kind": self.kind, "prompt": self.prompt, "derivation": self.derivation.value}


def seeds_for(
    *,
    state: HypothesisState,
    verdict: Verdict | None = None,
    underpowered: bool = False,
    open_objections: tuple[str, ...] = (),
) -> list[FollowUpSeed]:
    """What is worth asking next, given how this ended.

    Ordered by how much they are worth: an unresolved objection outranks a
    speculative generalisation, because the first is a debt against an
    existing claim and the second is only an idea.
    """
    seeds: list[FollowUpSeed] = []

    for objection in open_objections:
        seeds.append(
            FollowUpSeed(
                kind="settle_objection",
                prompt=(
                    f"An objection of type {objection!r} stands unresolved against this "
                    "work. Run the discriminating test it named."
                ),
                derivation=DerivationKind.REFUTATION_RESPONSE,
            )
        )

    if underpowered:
        seeds.append(
            FollowUpSeed(
                kind="repower",
                prompt=(
                    "The interval was too wide to separate the claimed effect from "
                    "none. Re-register the same comparison with enough seeds to "
                    "detect the effect it claims, so the next null means something."
                ),
                derivation=DerivationKind.SPECIALISATION,
            )
        )
        return seeds

    match verdict:
        case Verdict.REFUTED:
            seeds.append(
                FollowUpSeed(
                    kind="find_the_moderator",
                    prompt=(
                        "The effect is real and points the other way. Ask under what "
                        "condition the sign changes: a claim that holds in one regime "
                        "and reverses in another is a moderator, not a mistake."
                    ),
                    derivation=DerivationKind.REFUTATION_RESPONSE,
                )
            )
        case Verdict.INCONCLUSIVE:
            seeds.append(
                FollowUpSeed(
                    kind="claim_less",
                    prompt=(
                        "Something is there, smaller than was claimed. Re-register "
                        "with an effect size the evidence actually supports."
                    ),
                    derivation=DerivationKind.SPECIALISATION,
                )
            )
        case Verdict.NO_EFFECT:
            seeds.append(
                FollowUpSeed(
                    kind="probe_the_null",
                    prompt=(
                        "Nothing was there under these conditions. Ask whether the "
                        "null survives a condition where the mechanism would predict "
                        "an effect — a null that holds everywhere is worth more than "
                        "one measured once."
                    ),
                    derivation=DerivationKind.GENERALISATION,
                )
            )
        case Verdict.SUPPORTED:
            seeds.append(
                FollowUpSeed(
                    kind="test_generalisation",
                    prompt=(
                        "The claim held here. Ask where it stops holding: a claim "
                        "whose boundary is unknown has not been characterised."
                    ),
                    derivation=DerivationKind.GENERALISATION,
                )
            )
        case _:
            pass

    if state is HypothesisState.ABANDONED_BUDGET:
        seeds.append(
            FollowUpSeed(
                kind="cheaper_design",
                prompt=(
                    "The programme ran out of budget before this question was "
                    "answered. Ask whether a cheaper design could answer it, and what "
                    "it would give up."
                ),
                derivation=DerivationKind.SPECIALISATION,
            )
        )

    return seeds
